### PR TITLE
Update oauth2.gs

### PR DESCRIPTION
**Pull request by ayyar**
Use correct variable name for for logging errors.

### CODE REVIEW

**Comment by entaq** [comment]
Fixed a silly typo.

**Comment by pasie15** [comment]
Hey Arun, so I watched the google i/o presentation and am trying to use the ad hoc youtube report generator but I keep getiing a 401 invalid_client error on google, any help would be appreciated. I made sure to put in my client Id aswell as my client secret and is still getting an invalid user error. I would really love your help man, I pasted all the codein exactly how you posted them on github. Thanks

**Comment by entaq** [comment]
Hey @pasie15 usually this is you didn't create a correct OAuth client at https://console.developers.google.com/project. Make sure you create your own ID etc. 

Sidenote - I'm no longer working on this directly... I might not be able to reply in a timely manner.

**Comment by pasie15** [comment]
Hi Arun, thank you for getting back. I did that, created a client and got my own id and everything but I still have this problem, I am really confused. It just keeps giving me the same error.

**Pull request merged**
